MODEL:
  PRETRAIN_CHOICE: 'finetune'
  PRETRAIN_PATH: 'C:\Users\Administrator\.cache\torch\hub\checkpoints\resnet101_ibn_a-59ea0ac6.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'
  NAME: 'resnet101_ibn_a'
  DEVICE_ID: ('0')
  ID_LOSS_TYPE: 'softmax'
  POOLING_METHOD: 'GeM'
  ID_LOSS_WEIGHT: 1.0
  TRIPLET_LOSS_WEIGHT: 1.0
  WEIGHTED_TRIPLET: True
  NO_MARGIN: True

INPUT:
  SIZE_TRAIN: [600, 600]
  SIZE_TEST: [600, 600]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10

DATASETS:
  NAMES: ('huawei')
  ROOT_DIR: ('../train_data')
  HARD_AUG: True

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 90
  BASE_LR: 0.02
  IMS_PER_BATCH: 96
  STEPS: [40, 70]
  GAMMA: 0.1
  WARMUP_FACTOR: 0.01
  WARMUP_EPOCHS: 10
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 1
  LOG_PERIOD: 600
  EVAL_PERIOD: 10000
  COSINE_MARGIN: 0.3
  COSINE_SCALE: 30
  CENTER_LOSS_WEIGHT: 0.0003
  FP16: False

TEST:
  IMS_PER_BATCH: 128
  RE_RANKING: True
  DB_QE: False
  WEIGHT: 'model_our/1229-a-1/resnet101_ibn_a_90.pth'
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'
  FLIP_FEATS: 'on'
  PATH: '../test_data_final/test_data_A'
  
OUTPUT_DIR: "model_our/1229-a-1/"


